dist: xenial
sudo: false
language: python

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libwebkitgtk-dev
      - libwebkitgtk-3.0-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk-3-dev
      - libgtk3.0
      - autoconf
      - build-essential
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - libpng16-16
      - libpng-dev
      - freeglut3
      - freeglut3-dev
      - libsm-dev
      - libnotify-dev
      - dpkg-dev
      - build-essential
      - libxtst-dev

install:
  - pip3 install --upgrade pip
  - pip3 install pathlib2 pytest docutils pygments
  - pip3 install wxPython
  - python setup.py install


script:
  pytest

notifications:
  email: false